# Generated by Django 5.1.4 on 2025-01-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_slug"),
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="wishlist", name="items",),
        migrations.AddField(
            model_name="wishlist",
            name="products",
            field=models.ManyToManyField(related_name="wishlists", to="store.product"),
        ),
    ]
