# Generated by Django 5.1.4 on 2025-01-09 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
