# Generated by Django 5.1.4 on 2025-01-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_comment_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
