# Generated by Django 5.1.4 on 2025-01-16 18:20

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_discount"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="product",
            managers=[("products", django.db.models.manager.Manager()),],
        ),
    ]
