# Generated by Django 5.1.4 on 2025-01-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="none", max_length=255, unique=True),
        ),
    ]
